use types::*;
use registers::Register;

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Instruction {
	Mov(Register, Register),
	Movi(Register, Halfword),
	Movw(Register, Word),
	Lb(Register, Register, Tryte),
	Lh(Register, Register, Tryte),
	Lw(Register, Register, Tryte),
	Sb(Register, Register, Tryte),
	Sh(Register, Register, Tryte),
	Sw(Register, Register, Tryte),
	Add(Register, Register, Register),
	Addi(Register, Halfword),
	Mul(Register, Register),
	Muli(Register, Halfword),
	Not(Register, Register),
	And(Register, Register, Register),
	Andi(Register, Halfword),
	Or(Register, Register, Register),
	Ori(Register, Halfword),
	Shf(Register, Register, Register),
	Shfi(Register, Halfword),
	Cmp(Register, Register, Register),
	Jmp(Label),
	Jr(Register),
	JT(Register, Label),
	J0(Register, Label),
	J1(Register, Label),
	JT0(Register, Label),
	JT1(Register, Label),
	J01(Register, Label),
	Call(Label),
	Callr(Register),
	Ret,
	Sys,
	Brk,
	Halt,
}
